name: choomai_bot

services:
  node_bot:
    container_name: choomai_bot
    image: ghcr.io/choomai/choomai-bot:latest
    env_file: .env
    volumes:
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock:rw
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    container_name: choomai_redis
    image: redis:8-alpine
    user: redis
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      start_period: 1s
    restart: unless-stopped
